name = "AbbreviatedStackTraces"
uuid = "ac637c84-cc71-43bf-9c33-c1b4316be3d4"
authors = ["Nicholas Bauer <nicholasbauer@outlook.com>"]
version = "0.1.1"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
julia = "1.6"
